ALTER TABLE "ai_reports" ADD COLUMN IF NOT EXISTS "rubricProblemSolving" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ai_reports" ADD COLUMN IF NOT EXISTS "rubricCommunication" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ai_reports" ADD COLUMN IF NOT EXISTS "rubricCodeQuality" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ai_reports" ADD COLUMN IF NOT EXISTS "rubricEdgeCases" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ai_reports" ADD COLUMN IF NOT EXISTS "rubricSpeed" INTEGER NOT NULL DEFAULT 0;
